Minor fixes

diff --git a/un-seal b/un-seal
--- a/un-seal
+++ b/un-seal
@@ -2,7 +2,7 @@
 
 # ---
 # un-seal: A helper script to initialize or unseal a Juju-deployed Vault charm.
-# version: 5.4.0
+# version: 5.4.1
 #
 # This script automatically finds the Juju leader unit for the Vault
 # charm.
@@ -32,7 +32,7 @@
 set -euo pipefail
 
 # --- Configuration ---
-SNAP_VERSION=${SNAP_VERSION:-"5.4.0-script"}
+SNAP_VERSION=${SNAP_VERSION:-"5.5.0-script"}
 
 CHARM_NAME="vault" # Default Juju charm name
 KEY_SHARES=3 # Default keys generated
@@ -426,12 +426,6 @@ check_and_heal_unit() {
         exit 1
     fi
 
-    # Probe the actual service status. If this command fails (non-zero exit), the service is down.
-    local service_is_down=false
-    if ! $JUJU $JUJU_EXEC --unit "$unit_name" -- systemctl is-active $VAULT_SERVICE >/dev/null 2>&1; then
-        service_is_down=true
-    fi
-
     # Define boolean conditions for readability.
     local hook_failed=false
     [[ "$vault_status" == "error" && "$vault_message" == *"hook failed"* ]] && hook_failed=true
@@ -442,14 +436,25 @@ check_and_heal_unit() {
     local modern_vault_stuck=false
     [[ "$vault_status" == "waiting" && "$vault_message" == *"not yet available"* ]] && modern_vault_stuck=true
 
+    local is_juju_stuck=false
+    if [[ "$hook_failed" == "true" || "$legacy_vault_stuck" == "true" || "$modern_vault_stuck" == "true" ]]; then
+        is_juju_stuck=true
+    fi
+
+    # Probe the actual service status. If this command fails (non-zero exit), the service is down.
+    local service_is_down=false
+    if ! $JUJU $JUJU_EXEC --unit "$unit_name" -- systemctl is-active $VAULT_SERVICE >/dev/null 2>&1; then
+        service_is_down=true
+    fi
+
     # Restart service if vault is error/hook failed, but router is not blocked (or doesn't exist).
-    if [[ "$hook_failed" == "true" || "$legacy_vault_stuck" == "true" || "$modern_vault_stuck" == "true" || "$service_is_down" == "true" ]]; then
+    if [[ "$is_juju_stuck" == "true" || "$service_is_down" == "true" ]]; then
         echo ""
 
-        if [ "$service_is_down" == "true" ]; then
-            echo -e "  Detected that '$VAULT_SERVICE' is ${BRED}DOWN${NC} on $unit_name (despite Juju status: '$vault_status - $vault_message')."
-        else
+        if [ "$is_juju_stuck" == "true" ]; then
             echo -e "  Detected ${BYELLOW}stuck${NC} state on $unit_name ($vault_status - $vault_message)."
+        else
+            echo -e "  Detected that '$VAULT_SERVICE' is ${BRED}DOWN${NC} on $unit_name."
         fi
 
         echo -e "    Database connection appears OK (or N/A). Attempting to restart '$VAULT_SERVICE'..."
